apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-mq-pvc-mq-0
  namespace: rabbit
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
