apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
