apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-postgres-pvc-postgres-0
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
