apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mongodb-pvc-mongodb-0
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
