apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: db
  labels:
    svc: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    svc: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: db
spec:
  selector:
    matchLabels:
      svc: mongodb # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        svc: mongodb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:4.0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        volumeMounts:
        - name: db-mongodb-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: db-mongodb-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 2Gi
